In [1]:
import pickle
import numpy as np

In [2]:
def load_pickle(data_path):
    with open(data_path, 'rb') as f:
        return pickle.load(f)

In [83]:
def is_equal(a):
    x_bk = load_pickle('../../data/mnist_bk/{}.p'.format(a))
    print(x_bk.shape)
    x = load_pickle('../../data/preprocessed_data/mnist/{}.p'.format(a))
    print(x.shape)
    print(a+': ', np.equal(x_bk, x).all())

In [84]:
is_equal('x_train')
is_equal('x_test')
is_equal('x_valid')
is_equal('y_train')
is_equal('y_test')
is_equal('y_valid')
is_equal('imgs_train')
is_equal('imgs_test')
is_equal('imgs_valid')

(55000, 28, 28, 1)
(55000, 28, 28, 1)
x_train:  False
(10000, 28, 28, 1)
(10000, 28, 28, 1)
x_test:  False
(5000, 28, 28, 1)
(5000, 28, 28, 1)
x_valid:  False
(55000, 10)
(55000, 10)
y_train:  False
(10000, 10)
(10000, 10)
y_test:  False
(5000, 10)
(5000, 10)
y_valid:  False
(55000, 28, 28, 1)


FileNotFoundError: [Errno 2] No such file or directory: '../../data/preprocessed_data/mnist/imgs_train.p'

In [85]:
y = np.argmax(load_pickle('../../data/mnist_bk/y_test.p'), axis=-1)
y[:100]

array([9, 2, 3, 8, 6, 2, 4, 0, 9, 0, 8, 6, 3, 3, 3, 3, 6, 1, 7, 0, 0, 6, 3,
       5, 1, 7, 9, 4, 5, 0, 9, 6, 7, 0, 5, 6, 9, 7, 5, 9, 2, 5, 7, 4, 8, 8,
       6, 2, 0, 8, 7, 7, 6, 9, 0, 7, 8, 3, 7, 2, 4, 4, 0, 5, 6, 7, 7, 9, 5,
       1, 8, 8, 6, 2, 8, 8, 5, 9, 7, 3, 2, 4, 0, 5, 4, 7, 9, 4, 2, 0, 1, 7,
       0, 5, 6, 0, 5, 4, 7, 7])

In [86]:
y = np.argmax(load_pickle('../../data/preprocessed_data/mnist/y_test.p'), axis=-1)
y[:100]

array([8, 7, 1, 7, 1, 2, 1, 9, 5, 4, 5, 6, 3, 2, 0, 7, 6, 4, 6, 4, 5, 7, 8,
       9, 8, 7, 4, 3, 9, 4, 2, 2, 9, 7, 6, 7, 1, 2, 8, 3, 0, 6, 4, 0, 8, 7,
       8, 2, 9, 0, 4, 3, 4, 0, 7, 0, 7, 4, 6, 1, 9, 7, 2, 8, 8, 0, 1, 0, 5,
       1, 5, 1, 4, 9, 4, 8, 7, 3, 7, 8, 9, 1, 4, 4, 0, 2, 5, 7, 7, 5, 3, 0,
       6, 2, 4, 1, 6, 8, 6, 9])

In [87]:
y = load_pickle('../../data/source_data/mnist/test_labels.p')
y[:100]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6,
       5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5,
       1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3,
       0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6,
       9, 3, 1, 4, 1, 7, 6, 9], dtype=uint8)

In [ ]:
def is_equal(a):
    x_bk = load_pickle('../../data/source_data/{}.p'.format(a))
    print(x_bk.shape)
    x = load_pickle('../../data/preprocessed_data/mnist/{}.p'.format(a))
    print(a+': ', np.equal(x_bk, x).all())