In [21]:
import pickle
import numpy as np
import sys
import os
o_path = os.getcwd()
sys.path.append(os.path.dirname(o_path))
from models.utils import *
%matplotlib inline

In [14]:
save_path = '../../data/source_data/mnist_100'

train_imgs_ = load_pkls(save_path, 'train_images')
train_labels_ = load_pkls(save_path, 'train_labels')
square_grid_show_imgs(train_imgs_[:25], mode='L')
print(train_labels_[:25])

Loading ../../data/source_data/mnist_100/train_images.p from 7 parts...
Loading ../../data/source_data/mnist_100/train_images_0.p...
Loading ../../data/source_data/mnist_100/train_images_1.p...
Loading ../../data/source_data/mnist_100/train_images_2.p...
Loading ../../data/source_data/mnist_100/train_images_3.p...
Loading ../../data/source_data/mnist_100/train_images_4.p...
Loading ../../data/source_data/mnist_100/train_images_5.p...
Loading ../../data/source_data/mnist_100/train_images_6.p...


MemoryError: 

In [13]:
def load_pickle(data_path):
    with open(data_path, 'rb') as f:
        return pickle.load(f)

In [8]:
def is_equal(a):
    x_bk = load_pickle('../../data/mnist_bk/{}.p'.format(a))
    print(x_bk.shape)
    x = load_pickle('../../data/preprocessed_data/mnist/{}.p'.format(a))
    print(x.shape)
    print(a+': ', np.equal(x_bk, x).all())

In [9]:
is_equal('x_train')
is_equal('x_test')
is_equal('x_valid')
is_equal('y_train')
is_equal('y_test')
is_equal('y_valid')
is_equal('imgs_train')
is_equal('imgs_test')
is_equal('imgs_valid')

(55000, 28, 28, 1)
(55000, 28, 28, 1)
x_train:  True
(10000, 28, 28, 1)
(10000, 28, 28, 1)
x_test:  True
(5000, 28, 28, 1)
(5000, 28, 28, 1)
x_valid:  True
(55000, 10)
(55000, 10)
y_train:  True
(10000, 10)
(10000, 10)
y_test:  True
(5000, 10)
(5000, 10)
y_valid:  True
(55000, 28, 28, 1)
(55000, 28, 28, 1)
imgs_train:  True
(10000, 28, 28, 1)
(10000, 28, 28, 1)
imgs_test:  True
(5000, 28, 28, 1)
(5000, 28, 28, 1)
imgs_valid:  True


In [10]:
y = np.argmax(load_pickle('../../data/mnist_bk/y_test.p'), axis=-1)
y[:100]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6,
       5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5,
       1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3,
       0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6,
       9, 3, 1, 4, 1, 7, 6, 9])

In [11]:
y = np.argmax(load_pickle('../../data/preprocessed_data/mnist/y_test.p'), axis=-1)
y[:100]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6,
       5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5,
       1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3,
       0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6,
       9, 3, 1, 4, 1, 7, 6, 9])

In [12]:
y = load_pickle('../../data/source_data/mnist/test_labels.p')
y[:100]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6,
       5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5,
       1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3,
       0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6,
       9, 3, 1, 4, 1, 7, 6, 9], dtype=uint8)

In [ ]:
def is_equal(a):
    x_bk = load_pickle('../../data/source_data/{}.p'.format(a))
    print(x_bk.shape)
    x = load_pickle('../../data/preprocessed_data/mnist/{}.p'.format(a))
    print(a+': ', np.equal(x_bk, x).all())