In [1]:
import pickle
import numpy as np

In [2]:
def load_pickle(data_path):
    with open(data_path, 'rb') as f:
        return pickle.load(f)

In [3]:
def is_equal(a):
    x_bk = load_pickle('../../data/mnist_bk/{}.p'.format(a))
    print(x_bk.shape)
    x = load_pickle('../../data/preprocessed_data/mnist/{}.p'.format(a))
    print(x.shape)
    print(a+': ', np.equal(x_bk, x).all())

In [4]:
is_equal('x_train')
is_equal('x_test')
is_equal('x_valid')
is_equal('y_train')
is_equal('y_test')
is_equal('y_valid')
is_equal('imgs_train')
is_equal('imgs_test')
is_equal('imgs_valid')

(55000, 28, 28, 1)
(55000, 28, 28, 1)
x_train:  True
(10000, 28, 28, 1)
(10000, 28, 28, 1)
x_test:  True
(5000, 28, 28, 1)
(5000, 28, 28, 1)
x_valid:  True
(55000, 10)
(55000, 10)
y_train:  True
(10000, 10)
(10000, 10)
y_test:  True
(5000, 10)
(5000, 10)
y_valid:  True
(55000, 28, 28, 1)
(55000, 28, 28, 1)
imgs_train:  True
(10000, 28, 28, 1)
(10000, 28, 28, 1)
imgs_test:  True
(5000, 28, 28, 1)
(5000, 28, 28, 1)
imgs_valid:  True


In [5]:
y = np.argmax(load_pickle('../../data/mnist_bk/y_test.p'), axis=-1)
y[:100]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6,
       5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5,
       1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3,
       0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6,
       9, 3, 1, 4, 1, 7, 6, 9])

In [6]:
y = np.argmax(load_pickle('../../data/preprocessed_data/mnist/y_test.p'), axis=-1)
y[:100]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6,
       5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5,
       1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3,
       0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6,
       9, 3, 1, 4, 1, 7, 6, 9])

In [7]:
y = load_pickle('../../data/source_data/mnist/test_labels.p')
y[:100]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6, 6,
       5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2, 3, 5,
       1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4, 6, 4, 3,
       0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3, 6, 1, 3, 6,
       9, 3, 1, 4, 1, 7, 6, 9], dtype=uint8)

In [ ]:
def is_equal(a):
    x_bk = load_pickle('../../data/source_data/{}.p'.format(a))
    print(x_bk.shape)
    x = load_pickle('../../data/preprocessed_data/mnist/{}.p'.format(a))
    print(a+': ', np.equal(x_bk, x).all())